### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Mchtky** [gauravgupta45/Face_Recognition-Python-Project-4th-Sem#2]
Hello, when i click login i get this error.

File "C:/Users/Mucahit/Desktop/sons/Face_Recognition-Python-Project-4th-Sem-master/jerry.py", line 69, in recognize
    recognizer.read('trainer/trainer.yml')
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'

How can i fix ?

**Comment by Mchtky** [comment]
I found. Should be delete "dataset/dataset.txt" trainer search images in dataset folder. 
Note for other users : If webcam isn't open, replace VideoCapture(1) to VideoCapture(0)

**Comment by gauravgupta45** [comment]
Thanks for highlighting the issue. And yes if you want to use your laptop's webcam, 0 must be sent in the `VideoCapture()` as the parameter.
