### ISSUE TITLE
Login name and user error

### ISSUE THREAD

**Issue by Mchtky** [gauravgupta45/Face_Recognition-Python-Project-4th-Sem#3]
Hello, 
1-) I'm sign up with my own face to the app.
But when sign with different face (my friend face) login succeeds while login must fail.
2-) User names entered when signup, start from line 3 in the names_list.txt file.  That's why. When logging in, the login successful alert shows the wrong name. If the third person is sign up. The first person's name is printed when he logs on.

**Comment by gauravgupta45** [comment]
The algorithm I'm using for training face models is the  LBPH algorithm which is not much efficient. But it works best for smaller machines like our pc. While capturing the face, you must consider the lightning around you to get the best results. You could also increase the no. of images(dataset) you want to train. More datasets better results.
And I've removed the new line error(line: 252 of `jerry.py` script). The script will now check any empty line in `names_list.txt` file and will remove if there are any before writing the new names.
